name: DevOps Agent
description: Several actions to help you with your development workflow.
author: Josef Karamon
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-commit
  color: blue
inputs:
  command:
    description: |
      The command to run. It should be one of the following: 'jira', 'git'
    required: true
    default: ''
  subcommand:
    description: |
      The subcommand to run. It should be one of the following:
      For 'jira':
        - 'issue-pr-commenter': Creates a PR comment if the issue is incompletely specified.
        - 'update-status': Updates the status of a Jira issue.
        - 'add-comment': Adds a comment to a Jira issue.
      For 'git':
        - 'get-diff-data': Gets the git diff data for a pull request.
  args:
    description: "JSON string with arguments for the command / subcommand.\nFor the full list of arguments associated with each command, \nplease refer to the documentation. \n"
    required: false
    default: ''
runs:
  using: node20
  main: dist/index.js
